/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.spritemethodtest;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int background_works=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int skate1=0x7f020003;
        public static final int skate2=0x7f020004;
        public static final int skate3=0x7f020005;
    }
    public static final class id {
        public static final int GLSettings=0x7f050008;
        public static final int animateSprites=0x7f050004;
        public static final int methodCanvas=0x7f050006;
        public static final int methodOpenGL=0x7f050007;
        public static final int renderMethod=0x7f050005;
        public static final int runTest=0x7f05000c;
        public static final int settingDrawTexture=0x7f05000a;
        public static final int settingVBO=0x7f05000b;
        public static final int settingVerts=0x7f050009;
        public static final int spriteCount=0x7f050003;
        public static final int widget38=0x7f050002;
        public static final int widget39=0x7f050000;
        public static final int widget40=0x7f050001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int AnimateTitle=0x7f040004;
        public static final int CanvasTitle=0x7f040005;
        public static final int OpenGLTitle=0x7f040006;
        public static final int RunTestTitle=0x7f04000a;
        public static final int SpriteTitle=0x7f040003;
        public static final int UseDrawTextureTitle=0x7f040008;
        public static final int UseVBOTitle=0x7f040009;
        public static final int UseVertsTitle=0x7f040007;
        public static final int app_name=0x7f040000;
        public static final int dialog_ok=0x7f040001;
        public static final int dialog_title=0x7f040002;
    }
}
