/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.beust.android.translate;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int babelfish=0x7f020000;
        public static final int cn=0x7f020001;
        public static final int de=0x7f020002;
        public static final int es=0x7f020003;
        public static final int fr=0x7f020004;
        public static final int gr=0x7f020005;
        public static final int it=0x7f020006;
        public static final int jp=0x7f020007;
        public static final int kr=0x7f020008;
        public static final int nl=0x7f020009;
        public static final int pt=0x7f02000a;
        public static final int ru=0x7f02000b;
        public static final int tw=0x7f02000c;
        public static final int us=0x7f02000d;
    }
    public static final class id {
        public static final int about=0x7f07000f;
        public static final int from=0x7f070001;
        public static final int input=0x7f070002;
        public static final int languages=0x7f070005;
        public static final int menu_group_layers=0x7f07000b;
        public static final int most_recent=0x7f07000c;
        public static final int output=0x7f070004;
        public static final int progress_bar=0x7f070007;
        public static final int random_word=0x7f07000e;
        public static final int show_history=0x7f07000d;
        public static final int sort=0x7f07000a;
        public static final int status=0x7f070008;
        public static final int to=0x7f070003;
        public static final int translate=0x7f070006;
        public static final int translation=0x7f070009;
        public static final int webview=0x7f070000;
    }
    public static final class layout {
        public static final int about_dialog=0x7f030000;
        public static final int history_activity=0x7f030001;
        public static final int history_record=0x7f030002;
        public static final int language_dialog=0x7f030003;
        public static final int language_entry=0x7f030004;
        public static final int main=0x7f030005;
        public static final int translate_activity=0x7f030006;
    }
    public static final class menu {
        public static final int history_activity_menu=0x7f060000;
        public static final int translate_activity_menu=0x7f060001;
    }
    public static final class raw {
        public static final int dictionary=0x7f040000;
    }
    public static final class string {
        public static final int about=0x7f050005;
        public static final int about_message=0x7f050007;
        public static final int about_title=0x7f050006;
        /**   History 
         */
        public static final int clear_history=0x7f05000c;
        public static final int error=0x7f050001;
        public static final int found_translation=0x7f050003;
        public static final int languages=0x7f05000f;
        public static final int most_recent=0x7f05000e;
        public static final int random_word=0x7f05000b;
        public static final int retrieving_translation=0x7f050002;
        public static final int send_email=0x7f050008;
        public static final int show_history=0x7f050004;
        public static final int sort=0x7f05000d;
        public static final int text_to_translate=0x7f050009;
        /**   TranslateActivity 
         */
        public static final int translate_activity=0x7f050000;
        public static final int translate_from=0x7f050010;
        public static final int translate_to=0x7f050011;
        public static final int translation=0x7f05000a;
    }
}
