/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.wikinotes;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int parchmentbase=0x7f020001;
    }
    public static final class id {
        public static final int body_search=0x7f050004;
        public static final int body_search_button=0x7f050005;
        public static final int cancelButton=0x7f050003;
        public static final int confirmButton=0x7f050002;
        public static final int noteEdit=0x7f050001;
        public static final int noteview=0x7f050000;
        public static final int title_search_button=0x7f050006;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int wiki_note_edit=0x7f030001;
        public static final int wiki_search=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int cancel_button=0x7f040004;
        public static final int confirm_button=0x7f040003;
        public static final int delete_message=0x7f04000b;
        public static final int delete_title=0x7f04000a;
        public static final int menu_delete=0x7f040009;
        public static final int menu_edit=0x7f040005;
        public static final int menu_home=0x7f040006;
        public static final int menu_list=0x7f040008;
        public static final int menu_search=0x7f040007;
        public static final int no_button=0x7f04000d;
        public static final int recent_changes=0x7f04000f;
        public static final int search_body=0x7f040010;
        public static final int search_results=0x7f04000e;
        public static final int search_title=0x7f040012;
        public static final int search_titles=0x7f040011;
        public static final int start_page=0x7f040013;
        public static final int wiki_editing=0x7f040002;
        public static final int wiki_title=0x7f040001;
        public static final int yes_button=0x7f04000c;
    }
}
